# docker-compose.yml
version: '2'
services:

  prometheus:
    build: ./prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/opt/prometheus/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/opt/prometheus/prometheus/console_libraries'
      - '--web.console.templates=/opt/prometheus/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    # restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitor-net

  node-exporter:
    image: prom/node-exporter:latest
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - monitor-net
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    expose:
      - 9093
    volumes:
      - ./alertmanager/:/opt/prometheus/alertmanager
    restart: always
    command:
      - '--config.file=/opt/prometheus/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    networks:
      - monitor-net

  # alertmanager:
  #  build: ./alertmanager
  #  command:
  #    - '--config.file=/alertmanager.yml'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  monitor-net:
    driver: bridge
