global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'my-monitor'

rule_files:
  - 'prometheus.rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "192.168.11.7:9093"

scrape_configs:
  - job_name: 'node'
    scrape_interval: '15s'
    static_configs:
      - targets: ['192.168.1.243:9100', '192.168.1.16:9100']
        labels:
          alias: db1

  - job_name: mysql
    static_configs:
      - targets: ['192.168.1.243:9104']
        labels:
          alias: db1

  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: "5s"
    static_configs:
     - targets: ['192.168.11.7:9090']

  - job_name:       'example-random'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.243:80', '192.168.11.7:8081']
        labels:
          group: 'production'
      - targets: ['192.168.1.243:8000']
        labels:
          group: 'canary'

  - job_name: 'pve'
    static_configs:
      - targets: 
        - '192.168.1.235' #zeus
        - '192.168.1.95' #newton
        - '192.168.1.9' #faraday
        - '192.168.1.81' #fourier
        - '192.168.1.53' #braun

    metrics_path: /pve
    params:
      module: ['default']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.11.7:9221  # PVE exporter.

