global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'my-monitor'

rule_files:
  - 'prometheus.rules.yml'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "200.9.38.7:9093"

scrape_configs:
  - job_name: 'node'
    
    scrape_interval: '15s'

    static_configs:
      - targets: ['200.9.38.81:9100']

  - job_name: 'prometheus'
   
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: "5s"
   
    static_configs:
     - targets: ['200.9.38.7:9090']

  - job_name:       'example-random'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['200.9.38.81:80', '200.9.38.7:8081']
        labels:
          group: 'production'

      - targets: ['200.9.38.81:8000']
        labels:
          group: 'canary'

  - job_name: 'pve'

    static_configs:
      - targets: 
        - '200.9.37.217'

    metrics_path: /pve
    params:
      module: ['default']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 200.9.38.7:9221  # PVE exporter.

